#!/bin/bash

# This is a management script to track updates in the build environment and
# autobuild folder, including the option to generate lists of routers that
# need a rebuild or are missing from autobuild.

# This script is dependent upon jshon and the rooter build package.

######
#
# IMPORTANT: you MUST configure a link in your user's home config directory
# pointing to the directory where these conf files are actually stored.
#
source ~/.config/autobuild19/autobuild19.conf
#
######

splitout() {
        # Used to output the same text to both log and standard output.
        # If running in a Docker container, will send all output to
        # stdout instead.
        if [ -f /.dockerenv ] ; then
                echo "$*" >> /proc/1/fd/1
                if [ "$(readlink -f /proc/$$/fd/1)" != "$(readlink -f /proc/1/fd/1)" ] ; then echo "$*" >> /proc/$$/fd/1 ; fi
        else
                logger -t autobuilder "$*"
                echo "$*"
        fi
}

splitecho() {
        # Used to output the same text to standard output.
        # If running in a Docker container, will send all output to
        # stdout of #1 process instead.
        if [ -f /.dockerenv ] ; then
                echo "$*" >> /proc/1/fd/1
                if [ "$(readlink -f /proc/$$/fd/1)" != "$(readlink -f /proc/1/fd/1)" ] ; then echo "$*" >> /proc/$$/fd/1 ; fi
        else
                echo "$*"
        fi
}

is_int() { case ${1#[-+]} in '' | *[!0-9]* ) return 1;; esac ;}

testdir() {
	if [ -d $1 ] ; then
		return 0
	else
		# Error - critical directory missing
        	splitecho 1>&2 "Directory $1 missing!"
        	splitecho 1>&2 "Check configuration file $CONF"
        	exit 1
        fi
}

extract_date() {
        MYDATE=${1##*-GO}
        MYDATE=${MYDATE%.zip}
        MYDATE=${MYDATE%$SUFFIX}
}

abexecute() {
	# Check to make sure we didn't get a null list.
	COUNT=$(echo $* | wc -w)
	if [ $COUNT -gt "0" ] ; then
		# Some routers provided.
		echo "Sending list $* to trigger file $TRIGGERFILE6"
		echo "$*" >> $TRIGGERFILE
	else
		# Empty list! Do nothing.
		echo "No routers in execute list - not executing trigger."
	fi
}

abhelp() {
cat 1>&2 <<EndOfHelp
Usage: abmanage [ -cep ] COMMAND [ parameter ]

Options:

   -e		Execute a build using the resulting router list.

   -p		Perform a git pull before performing the command.

Commands:

   HELP		Display this usage message.

   NEW		List routers which have no Autobuild images.

   PRUNE count	Prune older images if router has more than
   		the given count available in server directory.

   STALE days	List routers whose autobuild images are at least
   		the given number of days old.

   STATUS	List all routers in catalog, with summary of number
   		of images, earliest, and latest.

   STOP		Stop the currently running build loop after the
   		completion of the current image (clean).

   STRAY	List all image files in the build directory which
   		no longer have a name in the catalog in a matching
   		format. This will usually represent routers with a
   		recent name change, which would be missed by a
   		prune action. Listed routers will be moved to
   		the trash directory in the conf file.

EndOfHelp
exit 1
}

abnew() {
	# Go through the list of routers, and add any router to OUTLIST that
	# doesn't have at least one image file in SERVEDIR.
	RLIST=$(jshon -k < $JSON | sort)
	for ROUTER in $RLIST
	do
		MOD=$(jshon -e "$ROUTER" -e mod < $JSON)
		MOD="${MOD%\"}"
		MOD=${MOD#\"}
		COUNT=$(ls $SERVEDIR | grep -- "$SUFFIX.zip" | grep -c "$MOD-GO")
		if [ ! "$COUNT" -gt "0" ] ; then
			OUTLIST="$OUTLIST $ROUTER"
		fi
	done
	# OUTLIST now contains routers with no images built
	splitecho $OUTLIST

	# If execute flag set, execute an autobuild based on the output list.
	[ "$EXECUTE" -eq "0" ] && abexecute $OUTLIST
}

abprune() {
	# For a given number of images to keep, prune any superfluous images
	# over that number, starting with the oldest. Move the pruned images
	# into the trash directory set in the conf file.
	# Error out if an execute flag was passed:
        [ "$EXECUTE" -eq "0" ] && splitecho "PRUNE command does not support -e flag." && abhelp

	PTTL="0"

	RLIST=$(jshon -k < $JSON | sort)
        for ROUTER in $RLIST
        do
                MOD=$(jshon -e "$ROUTER" -e mod < $JSON)
                MOD="${MOD%\"}"
                MOD=${MOD#\"}
                COUNT=$(ls $SERVEDIR | grep -- "$SUFFIX.zip" | grep -c "$MOD-GO")
                if [ "$COUNT" -gt "$1" ] ; then
                	# This router needs pruning. Make the list:
                	PCOUNT=$(expr "$COUNT" - "$1")
                	PLIST=$(ls $SERVEDIR | grep -- "$SUFFIX.zip" | grep "$MOD-GO" | head -n "$PCOUNT")
                	for PRUNEFILE in $PLIST ; do
                		mv $SERVEDIR/$PRUNEFILE $TRASH/
                	done

                	# Files pruned for this router. Add to results list.
			[ -n "$OUTLIST" ] && OUTLIST="${OUTLIST}, "
                	OUTLIST="${OUTLIST}${ROUTER}: $PCOUNT"
                	PTTL=$(expr "$PTTL" + "$PCOUNT")
                fi
        done

        # Print a summary of results.
        splitecho "Pruned $PTTL images: $OUTLIST"
}

abpull() {
	splitecho "Executing git pull of build environment:"
	git pull &>/dev/null
	if [ $? -ne "0" ] ; then
		splitecho "Error during git pull, aborting."
		exit 1
	fi
}

abstale() {
        # Go through the list of routers, and add any router to OUTLIST that
        # has images, and its newest image older than $1 days old (compared
        # in seconds since epoch)
	TODAY=$(date +%s)
	AGELIMIT=$(expr $1 \* 86400) # 86400 seconds in a day
	CUTOFF=$(expr $TODAY - $AGELIMIT)

        RLIST=$(jshon -k < $JSON | sort)
        for ROUTER in $RLIST
        do
                MOD=$(jshon -e "$ROUTER" -e mod < $JSON)
                MOD="${MOD%\"}"
                MOD=${MOD#\"}
                COUNT=$(ls $SERVEDIR | grep -- "$SUFFIX.zip" | grep -c "$MOD-GO")
                if [ "$COUNT" -gt "0" ] ; then
                	# This router has at least 1 existing image.
                	FRONT="$MOD-GO"
                	LATEST=$(ls $SERVEDIR | grep -- "$SUFFIX.zip" | grep "$FRONT" | tail -n 1)
                	# Trim the front and back off to get the date.
                	extract_date $LATEST
                	LATEST=$MYDATE
                	RDATESEC=$(date -d $LATEST +%s)
			if [ "$RDATESEC" -lt "$CUTOFF" ] ; then
				# Newest router image is older than cutoff
	                        OUTLIST="$OUTLIST $ROUTER"
	                fi
                fi
        done
        # OUTLIST now contains routers with no images built
        splitecho $OUTLIST

        # If execute flag set, execute an autobuild based on the output list.

	[ "$EXECUTE" -eq "0" ] && abexecute $OUTLIST
}

abstatus() {
	# Print a human-formatted status report.
	# Error out if an execute flag was passed:
	[ "$EXECUTE" -eq "0" ] && splitecho "STATUS command does not support -e flag." && abhelp

	# Get the key list:
	RLIST=$(jshon -k < $JSON | sort)

	# Find the longest router key name length:
	KEYLEN="0"
	for ROUTER in $RLIST
	do
		if [ ${#ROUTER} -gt "$KEYLEN" ] ; then
			KEYLEN="${#ROUTER}"
		fi
	done

	# Set width of key field to KEYLEN + 2
	KEYLEN=$(expr "$KEYLEN" + 2)

	# Report heading:
	echo "Autobuild System Status:"
	echo "   $(date)"
	echo "   $(echo $RLIST | wc -w) in catalog."
	LINEOUT=$( printf  "%${KEYLEN}s  %-5s%-12s%-12s" "MODEL" "QTY" "NEWEST" "OLDEST" )
	echo "$LINEOUT"

	for ROUTER in $RLIST
	do
		# For each router in list, output a status line.

		# Get file name and image count:
		MOD=$(jshon -e "$ROUTER" -e mod < $JSON)
                MOD="${MOD%\"}"
                MOD=${MOD#\"}
                COUNT=$(ls $SERVEDIR | grep -- "$SUFFIX.zip" | grep -c "$MOD-GO")

                # Get the oldest date:
                OLDEST=$(ls $SERVEDIR | grep -- "$SUFFIX.zip" | grep "$MOD-GO" | head -n 1)
                extract_date "$OLDEST"
                OLDEST="$MYDATE"

                # Get the newest date:
                NEWEST=$(ls $SERVEDIR | grep -- "$SUFFIX.zip" | grep "$MOD-GO" | tail -n 1)
                extract_date "$NEWEST"
                NEWEST="$MYDATE"

                # Print the status line.
                LINEOUT=$( printf  "%${KEYLEN}s  %-5s%-12s%-12s\n" "$ROUTER" "$COUNT" "$NEWEST" "$OLDEST" )
                echo "$LINEOUT"
	done
}

abstop() {
	# Stop the currently running test loop, wait for it to exit, and
	# then clean up the stop file.

	if [ ! -f $PIDFILE ] ; then
		splitecho "PID file not found, there is not an autobuild instance running."
		exit 1
	fi

	splitecho "Running build loop has PID $(cat $PIDFILE)"
	splitecho "Placing stop trigger file at $STOPFILE"

	touch $STOPFILE

	splitecho "Waiting for current image to finish cleanly:"

	# Sit in a loop while we wait for it to finish. Print a . every five seconds.

	while [ -f $PIDFILE ] ; do
		echo -n '.'
		sleep 5
	done

	splitecho ""
	splitecho "Current running build loop has exited."
	splitecho "Please be aware there may still be other builds queued,"
	splitecho "There are $(ps -e | grep -c abtrigger) copies of abtrigger waiting."
	if [ ! -f /.dockerenv ] ; then
		echo "You may choose to wait at the following prompt for other copies to cancel."
		echo
		read -n 1 -s -r -p "Press any key to remove stopfile and continue"
		echo
	fi

	rm $STOPFILE

	splitecho "Stopfile removed."
}

abstray() {
	# Find all image files in serve folder not in the catalog, report
	# them in an output list, and move them all to the trash folder.

	# Get a starting list of all non-html files in the directory, filtered
	# by the current SUFFIX. This enables sharing output directory between
	# multiple autobuild images, without the different autobuild systems
	# wrecking each others files.
	DIRLIST=$(ls -1 "$SERVEDIR" | grep -- "$SUFFIX.zip" | grep -v ".html")

	# Get a list of all the routers
	RLIST=$(jshon -k < $JSON | sort)

	# Cycle through the router list and remove all valid images from list.
	for ROUTER in $RLIST
        do
                MOD=$(jshon -e "$ROUTER" -e mod < $JSON)
                MOD="${MOD%\"}"
                MOD=${MOD#\"}
                # Remove everything from file list for this router:
                DIRLIST=$(echo "$DIRLIST" | grep -v "$MOD")
        done

        # Everything left in DIRLIST should now be a file or directory that
        # ISN'T a valid current catalog image (filtered by suffix).
        COUNT="0"
        OUTLIST=""
        for STRAY in $DIRLIST
        do
		if [ -f $SERVEDIR/$STRAY ] ; then
			# STRAY is a file, not a directory
	        	let COUNT++
        		OUTLIST="$OUTLIST $STRAY"
        		mv $SERVEDIR/$STRAY $TRASH/$STRAY
        	fi
        done

        # Report results.
        splitecho "Cleaned up $COUNT stray files: $OUTLIST"
}

COMMON=1	# All routers by default

EXECUTE=1	# Do not execute by default.
PULL=1		# Do not pull by default.
OUTLIST=""	# Start with blank output list.

# If in a Docker container, echo the command to log
if [ -f /.dockerenv ] ; then echo "$BASH_SOURCE $*" >> /proc/1/fd/1 ; fi

# Parse input flags.
while getopts cep flag ; do
	case "${flag}" in
		c) COMMON=0 ;;
		e) EXECUTE=0 ;;
		p) PULL=0 ;;
		"?") abhelp ;;
	esac
done

shift $((OPTIND -1))

# Check param count.
if [ $# -lt 1 -o $# -gt 2 ] ; then
	abhelp
fi

# Test for the important directories.
testdir $BUILDDIR && cd $BUILDDIR
testdir $SERVEDIR
JSON="$BUILDJSON"
if [ ! -f "$JSON" ] ; then
	 splitecho "$JSON missing!"
	 exit 1
fi

# Pull if requested
[ "$PULL" -eq "0" ] && abpull

# Sort on command.
case "${1^^}" in
	HELP) abhelp ;;
	NEW) abnew ;;
	PRUNE)
		if [ $# -eq 2 ] ; then
			is_int $2
			if [ $? -eq "0" ] ; then
				abprune "$2"
			else
				splitecho "Argument required: number of images to keep (integer)"
				abhelp
			fi
		else
			splitecho "Argument required: number of images to keep (integer)"
			abhelp
		fi
		;;
	STALE)
		if [ $# -eq 2 ] ; then
			is_int $2
			if [ $? -eq "0" ] ; then
				abstale "$2"
			else
				splitecho "Argument required: number of days (integer)"
                        	abhelp
			fi
		else
			splitecho "Argument required: number of days (integer)"
	                abhelp
		fi
		;;
	STATUS) abstatus ;;
	STRAY) abstray ;;
	STOP) abstop ;;
	*) abhelp ;;
esac

