#!/bin/bash

# This is a simple cron job to serve as an autobuild trigger.
# This is meant to run as a cron job every five minutes, and
# will trigger the build system based on a trigger file.
# If the trigger file contains a list of routers, it will
# run that list. Otherwise, it will trigger a full catalog
# build.

# This trigger system is meant to be used with autobuild when
# running on a standalone bare-metal system. For use within
# the docker-rooterbuilder system, use abtrigger.docker as a
# wrapper for this script instead of trying to set up cron
# within a docker container.

######
#
# IMPORTANT: you MUST edit the following line to point to the
# config file you want to use for this instance of the script.
#
source /build/autobuild/autobuild19.conf
#
######

splitout() {
        # Used to output the same text to both log and standard output.
        # If running in a Docker container, will send all output to
        # stdout instead.
        if [ -f /.dockerenv ] ; then
                echo "$*" >> /proc/1/fd/1
                if [ "$(readlink -f /proc/$$/fd/1)" != "$(readlink -f /proc/1/fd/1)" ] ; then echo "$*" >> /proc/$$/fd/1 ; fi
        else
                logger -t autobuilder "$*"
                echo "$*"
        fi
}

splitecho() {
        # Used to output the same text to standard output.
        # If running in a Docker container, will send all output to
        # stdout of #1 process instead.
        if [ -f /.dockerenv ] ; then
                echo "$*" >> /proc/1/fd/1
                if [ "$(readlink -f /proc/$$/fd/1)" != "$(readlink -f /proc/1/fd/1)" ] ; then echo "$*" >> /proc/$$/fd/1 ; fi
        else
                echo "$*"
        fi
}



if [ -f $TRIGGERFILE ] ; then
	# User has requested an autobuild run.

	# Check if sequence file exists; if not, start at 1.
	if [ ! -f $SEQFILE ] ; then
		splitout "abtrigger: Creating sequence file."
		echo "1" > $SEQFILE
	fi

	# Grab the sequence number
	SEQNO=`cat $SEQFILE`
	SEQNEXT="$SEQNO"
	let SEQNEXT++
	echo $SEQNEXT > $SEQFILE

	LIST=`tr '\n' ' ' < $TRIGGERFILE`
	LIST=`echo ${LIST^^} | tr -d '\r'`
	rm -f $TRIGGERFILE && splitout "abtrigger: Trigger file found and removed"
	# Above will import contents of the trigger file as a
	# single space delimited line.
	splitout "abtrigger: Sequence $SEQNO, trigger file list: $LIST"

	# Check if autobuilder running; if so, wait.
	while [ -f $PIDFILE ] ; do
		sleep 30
	done
	$AUTODIR/autobuild19 $SEQNO $LIST &>$AUTODIR/output/$SEQNO.build.txt &
	splitout "abtrigger: autobuild19 sequence $SEQNO triggered with list: $LIST"
fi

