#!/bin/bash

# Update the autobuilder script from the git.
# Simple operation, automated here because it
# allows for triggering it from outside a container.

# The script assumes you're already on a branch you want to be on.
# Use the -w /build/autobuild working directory if you're scripting
# the docker container to get into the right place.

cd /build/autobuild
git pull -q --ff-only

